name: platform_local_notifications
description: platform local notifications support all platform for local notify https://pub.dev/packages/platform_local_notifications
version: 0.1.0
homepage: https://github.com/hatemragab/platform_local_notifications
issue_tracker: https://github.com/hatemragab/platform_local_notifications/issues
repository: https://github.com/hatemragab/platform_local_notifications

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^16.1.0
  local_notifier: ^0.1.5
  flutter_cache_manager: ^3.3.1
  quick_notify:
    path: ./quick_notify
  another_flushbar: ^1.12.31-dev.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
platforms:
  android:
  ios:
  web:
  windows:
  macos:
  linux: